@extends('portal')
@section('title', $mode === 'login' ? 'Log in' : 'Create an account')
@section('content')
<div class="auth-layout"><div class="auth-aside"><div class="eyebrow"><span></span> Here with you</div><h1>{{ $mode === 'login' ? 'Good to have you back.' : 'A little help can change the whole day.' }}</h1><p>{{ $mode === 'login' ? 'Your next visit, and the people supporting it, are right here.' : 'Create an account to request a guide, or join as a hospital companion.' }}</p><div class="auth-aside-note"><i class="bi bi-shield-check"></i> Your account is private and protected.</div></div>
<div class="auth-form-panel"><div class="eyebrow"><span></span> {{ $mode === 'login' ? 'Welcome back' : 'Get started' }}</div><h2>{{ $mode === 'login' ? 'Log in to your account' : '' }}</h2><p class="auth-intro">{{ $mode === 'login' ? 'Enter your details to continue.' : 'It only takes a moment to get started.' }}</p>
<form method="POST" action="{{ $mode === 'login' ? route('login.store') : route('register.store') }}">@csrf
@if($mode === 'register')<label class="form-label" for="name">Your name</label><input class="form-control" id="name" name="name" value="{{ old('name') }}" autocomplete="name" required>@error('name')<small class="field-error">{{ $message }}</small>@enderror
<label class="form-label mt-3" for="phone">Phone <span class="optional">(optional)</span></label><input class="form-control" id="phone" name="phone" type="tel" value="{{ old('phone') }}" autocomplete="tel">
<fieldset class="role-picker"><legend class="form-label">I’m joining as</legend><div class="role-options"><label><input type="radio" name="role" value="patient" @checked(old('role', $selectedRole ?? 'patient') === 'patient')><span><i class="bi bi-person"></i> Patient or family</span></label><label><input type="radio" name="role" value="guide" @checked(old('role', $selectedRole ?? 'patient') === 'guide')><span><i class="bi bi-person-badge"></i> Hospital guide</span></label></div></fieldset>@endif
<label class="form-label mt-3" for="email">Email address</label><input class="form-control" id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required>@error('email')<small class="field-error">{{ $message }}</small>@enderror
<label class="form-label mt-3" for="password">Password</label><input class="form-control" id="password" name="password" type="password" autocomplete="{{ $mode === 'login' ? 'current-password' : 'new-password' }}" required>@error('password')<small class="field-error">{{ $message }}</small>@enderror
@if($mode === 'register')<label class="form-label mt-3" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required>@else<label class="remember-row mt-3"><input type="checkbox" name="remember" value="1"> Keep me signed in</label>@endif
<button class="btn btn-forest w-100 mt-4" type="submit">{{ $mode === 'login' ? 'Log in' : 'Create account' }} <i class="bi bi-arrow-right ms-2"></i></button></form>
<div class="auth-switch">{{ $mode === 'login' ? 'New to Hospital Sarthi?' : 'Already have an account?' }} <a href="{{ $mode === 'login' ? route('register') : route('login') }}">{{ $mode === 'login' ? 'Create an account' : 'Log in' }}</a></div><div class="auth-disclaimer"><i class="bi bi-info-circle me-1"></i> Guides provide practical, non-medical hospital support.</div></div></div>
@endsection
