@extends('portal')
@section('title', ucfirst($role).' dashboard')
@section('content')
<div class="dashboard-heading"><div><div class="eyebrow"><span></span> {{ ucfirst($role) }} workspace</div><h1>Hello, {{ auth()->user()->name }}.</h1><p>{{ $role === 'patient' ? 'Your visits and guide requests, all in one place.' : ($role === 'guide' ? 'Your profile, availability and upcoming visits.' : 'Keep hospital listings and guide verification up to date.') }}</p></div><span class="role-chip"><i class="bi {{ $role === 'patient' ? 'bi-person' : ($role === 'guide' ? 'bi-person-badge' : 'bi-shield-lock') }}"></i> {{ ucfirst($role) }}</span></div>
@if($role === 'patient')
    <section class="portal-section">
        <div class="section-title"><div><span class="eyebrow"><span></span> Your details</span><h2>Patient profile</h2></div></div>
        <form method="POST" action="{{ route('patient.profile.update') }}" class="portal-form">
            @csrf
            @method('PATCH')
            <div class="row g-3 mb-3">
                <div class="col-md-6"><label class="form-label" for="name">Patient name</label><input class="form-control" id="name" name="name" value="{{ old('name', auth()->user()->name) }}" maxlength="120" required></div>
            </div>
            @include('components.patient-profile-fields', ['patient' => auth()->user()])
            <div class="form-actions"><button class="btn btn-forest" type="submit">Save profile <i class="bi bi-check-lg ms-1"></i></button></div>
        </form>
    </section>
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Your visits</span><h2>Booking requests</h2></div><a href="{{ route('home') }}#find" class="text-action">Find a hospital <i class="bi bi-arrow-up-right"></i></a></div>
    @forelse($bookings as $booking)<article class="booking-row"><div class="booking-date"><strong>{{ $booking->visit_date->format('d') }}</strong><span>{{ $booking->visit_date->format('M Y') }}</span></div><div class="booking-details"><strong>{{ $booking->hospital->name }}</strong><span>{{ $booking->service }} · {{ $booking->start_time }}</span><small>Guide: {{ $booking->guideProfile->user->name }}</small></div><span class="status status-{{ $booking->status }}">{{ ucfirst($booking->status) }}</span>@if($booking->status === 'pending')<form method="POST" action="{{ route('bookings.cancel', $booking) }}">@csrf @method('DELETE')<button class="icon-button" aria-label="Cancel booking" title="Cancel booking"><i class="bi bi-x-lg"></i></button></form>@endif</article>@empty<div class="empty-panel"><i class="bi bi-calendar2-check"></i><strong>No visits booked yet.</strong><p>Find the hospital you’re visiting and choose a guide who covers it.</p><a class="btn btn-forest" href="{{ route('home') }}#find">Find a guide <i class="bi bi-arrow-right ms-2"></i></a></div>@endforelse
    </section>
@elseif($role === 'guide')
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Guide profile</span><h2>Your profile & availability</h2></div><span class="status {{ $profile?->is_verified ? 'status-accepted' : 'status-pending' }}">{{ $profile?->is_verified ? 'Verified' : 'Awaiting verification' }}</span></div>
    @if($profile)<form method="POST" action="{{ route('guide.profile.update') }}" class="portal-form">@csrf @method('PUT')<label class="form-label" for="bio">A little about you</label><textarea class="form-control" id="bio" name="bio" rows="3" maxlength="1200" placeholder="Share your hospital experience and how you support visitors.">{{ old('bio', $profile->bio) }}</textarea>
    <div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label" for="languages">Languages <span class="optional">(comma separated)</span></label><input class="form-control" id="languages" name="languages" value="{{ old('languages', implode(', ', $profile->languages ?? [])) }}" placeholder="Hindi, English"></div><div class="col-md-3"><label class="form-label" for="years_experience">Years of experience</label><input class="form-control" id="years_experience" name="years_experience" type="number" min="0" max="60" value="{{ old('years_experience', $profile->years_experience) }}" required></div><div class="col-md-3"><label class="form-label" for="hourly_rate">Hourly rate (₹)</label><input class="form-control" id="hourly_rate" name="hourly_rate" type="number" min="0" step="50" value="{{ old('hourly_rate', $profile->hourly_rate) }}" required></div></div>
    <fieldset class="hospital-picker"><legend class="form-label">Hospitals you cover</legend><div class="hospital-checks">@foreach($hospitals as $hospital)<label><input type="checkbox" name="hospitals[]" value="{{ $hospital->id }}" @checked(in_array($hospital->id, old('hospitals', $profile->hospitals->pluck('id')->all())))><span>{{ $hospital->name }} <small>{{ $hospital->city }}</small></span></label>@endforeach</div>@if($hospitals->isEmpty())<p class="help-text">No hospitals are listed yet. Check back after an admin adds your hospital.</p>@endif</fieldset>
    <fieldset class="availability-picker"><legend class="form-label">Weekly availability</legend><div class="availability-head"><span>DAY</span><span>FROM</span><span>UNTIL</span></div>@php($weeklyAvailability = $profile->availabilities->keyBy('weekday'))@foreach(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as $day => $dayName)@php($slot = $weeklyAvailability->get($day))<div class="availability-row"><strong>{{ $dayName }}</strong><input class="form-control" aria-label="{{ $dayName }} start time" type="time" name="availability[{{ $day }}][start_time]" value="{{ old('availability.'.$day.'.start_time', $slot ? substr($slot->start_time, 0, 5) : '') }}"><input class="form-control" aria-label="{{ $dayName }} end time" type="time" name="availability[{{ $day }}][end_time]" value="{{ old('availability.'.$day.'.end_time', $slot ? substr($slot->end_time, 0, 5) : '') }}"></div>@endforeach</fieldset>
    <label class="availability-toggle"><input type="checkbox" name="is_available" value="1" @checked(old('is_available', $profile->is_available))><span><strong>Accepting new bookings</strong><small>Turn this off whenever you’re unavailable.</small></span></label><div class="form-actions"><button class="btn btn-forest" type="submit">Save profile <i class="bi bi-arrow-right ms-2"></i></button><span>Only verified guides appear in patient search.</span></div></form>@endif
    </section>
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Patient requests</span><h2>Booking requests</h2></div></div>
    @forelse($bookings as $booking)<article class="booking-row"><div class="booking-date"><strong>{{ $booking->visit_date->format('d') }}</strong><span>{{ $booking->visit_date->format('M Y') }}</span></div><div class="booking-details"><strong>{{ $booking->hospital->name }} · {{ $booking->service }}</strong><span>{{ $booking->visit_date->format('D, d M') }} at {{ $booking->start_time }}</span><small>For {{ $booking->patient->name }}@if($booking->message) · {{ $booking->message }}@endif</small></div><span class="status status-{{ $booking->status }}">{{ ucfirst($booking->status) }}</span>@if($booking->status === 'pending')<form class="booking-actions" method="POST" action="{{ route('guide.bookings.respond', $booking) }}">@csrf @method('PATCH')<button class="btn btn-forest btn-sm" name="status" value="accepted">Accept</button><button class="btn btn-outline-danger btn-sm" name="status" value="rejected">Decline</button></form>@elseif($booking->status === 'accepted')<form class="booking-actions" method="POST" action="{{ route('guide.bookings.respond', $booking) }}">@csrf @method('PATCH')<button class="btn btn-forest btn-sm" name="status" value="received">Mark arrived</button></form>@endif</article>@empty<div class="empty-panel"><i class="bi bi-inbox"></i><strong>No booking requests yet.</strong><p>Keep your profile and availability current to help patients find you.</p></div>@endforelse
    </section>
@else
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Directory</span><h2>Add a hospital</h2></div></div><form method="POST" action="{{ route('admin.hospitals.store') }}" class="portal-form admin-hospital-form">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label" for="name">Hospital name</label><input class="form-control" id="name" name="name" required></div><div class="col-md-3"><label class="form-label" for="city">City</label><input class="form-control" id="city" name="city" required></div><div class="col-md-3"><label class="form-label" for="type">Type</label><input class="form-control" id="type" name="type" placeholder="Multispecialty"></div><div class="col-md-6"><label class="form-label" for="address">Address</label><input class="form-control" id="address" name="address" required></div><div class="col-md-3"><label class="form-label" for="phone">Phone</label><input class="form-control" id="phone" name="phone" type="tel"></div><div class="col-md-3"><label class="form-label" for="image_url">Image URL <span class="optional">(optional)</span></label><input class="form-control" id="image_url" name="image_url" type="url"></div></div><button class="btn btn-forest mt-3" type="submit">Add hospital <i class="bi bi-plus-lg ms-1"></i></button></form>
    <div class="admin-list">@forelse($hospitals as $hospital)<article class="admin-row"><span><strong>{{ $hospital->name }}</strong><small>{{ $hospital->city }} · {{ $hospital->address }}</small></span><span class="status {{ $hospital->is_active ? 'status-accepted' : 'status-rejected' }}">{{ $hospital->is_active ? 'Active' : 'Hidden' }}</span><form method="POST" action="{{ route('admin.hospitals.toggle', $hospital) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary btn-sm">{{ $hospital->is_active ? 'Hide listing' : 'Activate' }}</button></form></article>@empty<p class="help-text mt-4">No hospital listings yet.</p>@endforelse</div></section>
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Guide applications</span><h2>Review guide profiles</h2></div></div>@forelse($guides as $guide)<article class="admin-row"><span><strong>{{ $guide->user->name }}</strong><small>{{ $guide->user->email }} · {{ $guide->years_experience }} years’ experience · {{ implode(', ', $guide->languages ?? []) }}</small><small>{{ $guide->hospitals->pluck('name')->join(', ') ?: 'No hospitals selected' }}</small></span><span class="status {{ $guide->is_verified ? 'status-accepted' : 'status-pending' }}">{{ $guide->is_verified ? 'Verified' : 'Pending' }}</span><form method="POST" action="{{ route('admin.guides.verify', $guide) }}">@csrf @method('PATCH')<input type="hidden" name="is_verified" value="{{ $guide->is_verified ? 0 : 1 }}"><button class="btn btn-sm {{ $guide->is_verified ? 'btn-outline-danger' : 'btn-forest' }}">{{ $guide->is_verified ? 'Remove verification' : 'Verify guide' }}</button></form></article>@empty<p class="help-text">No guide profiles to review yet.</p>@endforelse</section>
    <section class="portal-section"><div class="section-title"><div><span class="eyebrow"><span></span> Recent activity</span><h2>Bookings</h2></div></div>@forelse($bookings as $booking)<article class="booking-row"><div class="booking-date"><strong>{{ $booking->visit_date->format('d') }}</strong><span>{{ $booking->visit_date->format('M Y') }}</span></div><div class="booking-details"><strong>{{ $booking->hospital->name }} · {{ $booking->service }}</strong><span>{{ $booking->patient->name }} with {{ $booking->guideProfile->user->name }}</span></div><span class="status status-{{ $booking->status }}">{{ ucfirst($booking->status) }}</span></article>@empty<div class="empty-panel"><i class="bi bi-calendar2"></i><strong>No bookings yet.</strong></div>@endforelse</section>
@endif
@endsection
