<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A little more support for the hospital visit ahead. Find a verified hospital guide for practical, non-medical assistance.">
    <title>Hospital Sarthi | A familiar face for the hospital visit ahead</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="{{ asset('css/site.css') }}" rel="stylesheet">
</head>
<body>
<div class="topline"><div class="container d-flex justify-content-between align-items-center"><span><i class="bi bi-heart-pulse me-2"></i>Practical help for the parts of a hospital visit that feel unfamiliar.</span><a href="#how-it-works">How it works <i class="bi bi-arrow-up-right ms-1"></i></a></div></div>
<nav class="navbar navbar-expand-lg site-nav" aria-label="Main navigation"><div class="container">
    <a class="navbar-brand brand" href="{{ url('/') }}"><span class="brand-mark"><i class="bi bi-plus-lg"></i></span><span>Aapka<span class="brand-light">sarthi</span><small> Jab Apno Ki Zarurat Ho</small></span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav mx-auto align-items-lg-center gap-lg-4"><li><a class="nav-link" href="#find">Find a hospital</a></li><li><a class="nav-link" href="#services">Services</a></li><li><a class="nav-link" href="#how-it-works">How it works</a></li><li><a class="nav-link" href="#faq">FAQs</a></li></ul><div class="nav-actions d-flex align-items-center gap-3">
        @auth<a class="nav-login" href="{{ route('dashboard') }}">My account</a>@else<a class="nav-login" href="{{ route('login') }}">Log in</a><a class="btn btn-forest btn-sm px-3" href="{{ route('register') }}">Get started <i class="bi bi-arrow-up-right ms-1"></i></a>@endauth
    </div></div>
</div></nav>
<main>
    <section class="hero-section"><div class="container hero-wrap"><div class="hero-copy">
        <div class="eyebrow eyebrow-light"><span></span>Verified companions, human support</div><h1>Get trusted personal<br>assitance<em>at the Hospital</em></h1>
        <p class="hero-lede">A trusted, verified companion by your side — helping you with registration, queues, doctor visits, tests, billing and everything in between.</br>For patients who need support. For families who want peace of mind.</p>
        <form class="search-panel" id="hospital-search-form" role="search"><label class="search-field" for="hospital-search"><i class="bi bi-geo-alt"></i><span><small>HOSPITAL OR CITY</small><input id="hospital-search" name="q" type="search" placeholder="Where do you need a hand?" autocomplete="off"></span></label><button class="btn btn-lime" type="button" x-data @click="$dispatch('open-book-guide-modal')">Find a guide <i class="bi bi-arrow-right ms-2"></i></button></form>
        <div class="search-results" id="search-results" aria-live="polite" hidden></div><div class="hero-note"><i class="bi bi-shield-check"></i> Verified guides <span></span> Human help, right where you need it</div>
    </div><div class="hero-visual"><img src="https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=85" alt="A bright, welcoming hospital corridor"><div class="photo-caption"><span class="caption-icon"><i class="bi bi-signpost-2"></i></span><span><strong>One step at a time.</strong><small>From the entrance to the next counter.</small></span></div><div class="photo-index">01 <span></span> 04</div></div></div><div class="hero-bottom"><div class="container d-flex flex-wrap justify-content-between gap-3"><span>Care beyond the clinic room.</span><span>Practical support. No medical advice.</span></div></div></section>
    <section class="trust-strip"><div class="container trust-grid"><div><strong>01</strong><span>Choose your hospital</span></div><div><strong>02</strong><span>Meet your guide</span></div><div><strong>03</strong><span>Arrive with a plan</span></div><div class="trust-end"><i class="bi bi-heart-fill"></i><span>Made for patients and the people beside them</span></div></div></section>
    <section class="section-pad" id="how-it-works"><div class="container"><div class="section-heading row align-items-end"><div class="col-lg-7"><div class="eyebrow"><span></span> A little less figuring it out</div><h2>Good support makes<br>room for <em>what matters.</em></h2></div><div class="col-lg-4 ms-lg-auto"><p>Hospital Sarthi pairs you with a verified guide for the practical details, so you can focus on being there for yourself or someone you love.</p></div></div><div class="steps-grid">
        <article class="step-item"><span class="step-number">01</span><span class="step-icon"><i class="bi bi-search"></i></span><h3>Find your hospital</h3><p>Search the hospital you’re visiting and see guides who know their way around.</p><a href="#find" aria-label="Search hospitals"><i class="bi bi-arrow-down-right"></i></a></article>
        <article class="step-item"><span class="step-number">02</span><span class="step-icon"><i class="bi bi-person-check"></i></span><h3>Choose your guide</h3><p>Compare verified profiles, language and availability, then send a booking request.</p><a href="#find" aria-label="Find a guide"><i class="bi bi-arrow-down-right"></i></a></article>
        <article class="step-item"><span class="step-number">03</span><span class="step-icon"><i class="bi bi-signpost-split"></i></span><h3>Go together</h3><p>Your guide helps with hospital navigation and the next practical step in your visit.</p><a href="#services" aria-label="Explore services"><i class="bi bi-arrow-down-right"></i></a></article>
    </div></div></section>
    <section class="services-section section-pad" id="services"><div class="container"><div class="section-heading row align-items-end"><div class="col-lg-7"><div class="eyebrow"><span></span> In-the-hospital support</div><h2>The little things,<br><em>handled together.</em></h2></div><div class="col-lg-4 ms-lg-auto"><p>Your guide is there for practical navigation and coordination. They never diagnose, treat or replace hospital staff.</p></div></div><div class="services-grid">
        <article class="service-item"><span class="service-icon"><i class="bi bi-door-open"></i></span><span class="service-no">01 / ARRIVAL</span><h3>Find the right place</h3><p>Entrance, department, OPD registration and where to go next.</p></article>
        <article class="service-item"><span class="service-icon icon-coral"><i class="bi bi-ticket-perforated"></i></span><span class="service-no">02 / APPOINTMENTS</span><h3>Tokens & queues</h3><p>Help understanding the queue flow and keeping track of your turn.</p></article>
        <article class="service-item"><span class="service-icon icon-blue"><i class="bi bi-eyedropper"></i></span><span class="service-no">03 / TESTS</span><h3>Tests & reports</h3><p>Locate diagnostic centres and report collection counters.</p></article>
        <article class="service-item"><span class="service-icon icon-yellow"><i class="bi bi-receipt"></i></span><span class="service-no">04 / CHECKOUT</span><h3>Billing & pharmacy</h3><p>Navigate payment counters, the pharmacy and discharge steps.</p></article>
    </div><div class="service-footnote"><i class="bi bi-info-circle"></i> Guides provide navigation and non-medical assistance only. Clinical questions should always go to your care team.</div></div></section>
    <section class="hospital-section section-pad" id="find"><div class="container"><div class="section-heading row align-items-end"><div class="col-lg-7"><div class="eyebrow"><span></span> Start with where you’re going</div><h2>Hospitals in your<br><em>corner of the city.</em></h2></div><div class="col-lg-4 ms-lg-auto"><p>Browse available hospitals, then find a guide who knows the layout and the little details.</p></div></div><div class="hospital-grid" id="popular-hospitals">
        @forelse(($hospitals ?? collect()) as $hospital)
            <article class="hospital-card"><div class="hospital-image"><img src="{{ $hospital->image_url ?: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=900&q=80' }}" alt="{{ $hospital->name }}" loading="lazy"><span><i class="bi bi-geo-alt-fill"></i> {{ $hospital->city }}</span></div><div class="hospital-content"><span class="hospital-type">{{ $hospital->type ?? 'HOSPITAL' }}</span><h3>{{ $hospital->name }}</h3><p>{{ $hospital->address }}</p><a href="{{ route('hospitals.guides', $hospital) }}">Meet the guides <i class="bi bi-arrow-up-right"></i></a></div></article>
        @empty
            <div class="directory-empty"><span><i class="bi bi-buildings"></i></span><div><strong>Your hospital could be here.</strong><p>We’re growing our verified hospital directory. Search above to check current listings.</p></div><a href="#contact">Suggest a hospital <i class="bi bi-arrow-up-right ms-1"></i></a></div>
        @endforelse
    </div><div class="directory-cta"><span>Not seeing your hospital?</span><a href="#contact">Tell us where you need support <i class="bi bi-arrow-right ms-1"></i></a></div></div></section>
    <section class="why-section section-pad"><div class="container why-layout"><div class="why-image"><img src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1100&q=85" alt="A care professional offering a reassuring conversation" loading="lazy"><div class="image-stamp"><i class="bi bi-heart"></i><span>Here for<br>the human side</span></div></div><div class="why-copy"><div class="eyebrow eyebrow-light"><span></span> A different kind of support</div><h2>Care isn’t only<br>what happens in<br><em>the consultation.</em></h2><p>It’s the walk to the right floor. The question about the next counter. The relief of not having to work it all out alone.</p><ul class="why-list"><li><i class="bi bi-check2"></i><span><strong>People, not just directions</strong><small>A real companion, there with you in person.</small></span></li><li><i class="bi bi-check2"></i><span><strong>Verified before they’re listed</strong><small>Every guide profile is reviewed by our team.</small></span></li><li><i class="bi bi-check2"></i><span><strong>You stay in control</strong><small>Choose who to meet and what support you need.</small></span></li></ul><a class="btn btn-lime" href="#find">Find your hospital <i class="bi bi-arrow-right ms-2"></i></a></div></div></section>
    <section class="reviews-section section-pad"><div class="container"><div class="section-heading row align-items-end"><div class="col-lg-7"><div class="eyebrow"><span></span> Words from families</div><h2>Sometimes, being there<br><em>is the whole thing.</em></h2></div><div class="col-lg-4 ms-lg-auto"><p>Every hospital visit is different. Here’s what practical, human support can feel like.</p></div></div><div class="review-grid">
        <article class="review-card"><div class="review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“I didn’t have to leave my mother alone to find the billing counter. That mattered more than I can explain.”</blockquote><div class="review-by"><span class="review-avatar avatar-green">AM</span><span><strong>Ananya M.</strong><small>Supported her mother</small></span><i class="bi bi-quote"></i></div></article>
        <article class="review-card review-featured"><div class="review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“We knew exactly where to go when we arrived. The whole day felt a little less overwhelming.”</blockquote><div class="review-by"><span class="review-avatar avatar-peach">RK</span><span><strong>Rahul K.</strong><small>Patient’s family member</small></span><i class="bi bi-quote"></i></div></article>
        <article class="review-card"><div class="review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“Having someone explain the steps and walk beside us gave me the confidence to manage on my own.”</blockquote><div class="review-by"><span class="review-avatar avatar-blue">SP</span><span><strong>Saira P.</strong><small>Hospital visitor</small></span><i class="bi bi-quote"></i></div></article>
    </div><p class="review-note">Illustrative examples. Replace with consented, verified customer reviews before launch.</p></div></section>
    <section class="faq-section section-pad" id="faq"><div class="container faq-layout"><div><div class="eyebrow"><span></span> Good to know</div><h2>A few things<br>you might be <em>wondering.</em></h2><p>Something else on your mind? We’re happy to help.</p><a href="#contact" class="faq-contact">Talk to our team <i class="bi bi-arrow-up-right"></i></a></div><div class="accordion faq-list" id="faqAccordion">
        <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqOne" aria-expanded="true" aria-controls="faqOne">What does a hospital guide do?<i class="bi bi-plus-lg"></i></button></h3><div id="faqOne" class="accordion-collapse collapse show" data-bs-parent="#faqAccordion"><div class="accordion-body">A guide meets you at the hospital and helps with practical navigation: finding departments, registration, queues, test centres, billing, pharmacy, reports and discharge steps.</div></div></div>
        <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqTwo" aria-expanded="false" aria-controls="faqTwo">Can a guide give medical advice?<i class="bi bi-plus-lg"></i></button></h3><div id="faqTwo" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">No. Guides provide non-medical assistance only. They do not diagnose, recommend treatment or interpret medical reports. Please direct clinical questions to your doctor or hospital care team.</div></div></div>
        <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqThree" aria-expanded="false" aria-controls="faqThree">Who can book a guide?<i class="bi bi-plus-lg"></i></button></h3><div id="faqThree" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">A patient or a family member can make a booking request. You can share who the visit is for and any practical support preferences when you book.</div></div></div>
        <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqFour" aria-expanded="false" aria-controls="faqFour">How are guides verified?<i class="bi bi-plus-lg"></i></button></h3><div id="faqFour" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">Every guide is reviewed by our admin team before their profile appears in search. Only approved profiles can receive booking requests.</div></div></div>
    </div></div></section>
    <section class="contact-band" id="contact"><div class="container contact-inner"><div><div class="eyebrow eyebrow-light"><span></span> We’re listening</div><h2>Where could a guide<br>make a difference?</h2></div><div><p>Suggest a hospital, ask a question, or tell us what would make your next visit easier.</p><a class="btn btn-lime" href="mailto:hello@hospitalsarthi.in">Write to us <i class="bi bi-arrow-up-right ms-2"></i></a></div></div></section>
+</main>
+<footer class="site-footer"><div class="container"><div class="footer-main"><div class="footer-brand"><a class="brand brand-footer" href="{{ url('/') }}"><span class="brand-mark"><i class="bi bi-plus-lg"></i></span><span>hospital<span class="brand-light">sarthi</span><small>HERE WITH YOU</small></span></a><p>A familiar face for the hospital visit ahead.</p></div><div class="footer-links"><div><strong>EXPLORE</strong><a href="#find">Find a hospital</a><a href="#services">Our services</a><a href="#how-it-works">How it works</a></div><div><strong>BE PART OF IT</strong><a href="{{ route('register', ['role' => 'guide']) }}">Become a guide</a><a href="#contact">Suggest a hospital</a><a href="#faq">FAQs</a></div><div><strong>YOUR ACCOUNT</strong><a href="{{ route('login') }}">Log in</a><a href="{{ route('register') }}">Create an account</a><a href="mailto:hello@hospitalsarthi.in">Contact us</a></div></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Hospital Sarthi. Here with you.</span><span>Hospital navigation support only. Not medical care or advice.</span><a href="#top" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;">Back to top <i class="bi bi-arrow-up"></i></a></div></div></footer>
@include('components.book-guide-modal')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="{{ asset('js/site.js') }}"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.9/dist/cdn.min.js"></script>
@stack('scripts')
+</body></html>
