@extends('portal')
@section('title', ucfirst($section).' management')
@section('content')
@php
    $sectionTitles = [
        'users' => 'User accounts', 'guides' => 'Guide profiles', 'hospitals' => 'Hospital directory',
        'services' => 'Booking services', 'bookings' => 'Bookings', 'payments' => 'Payments',
        'reviews' => 'Customer reviews', 'commission' => 'Commission settings',
    ];
    $sectionIcons = [
        'users' => 'bi-people', 'guides' => 'bi-person-badge', 'hospitals' => 'bi-hospital',
        'services' => 'bi-clipboard2-check', 'bookings' => 'bi-calendar2-check', 'payments' => 'bi-credit-card',
        'reviews' => 'bi-chat-square-text', 'commission' => 'bi-graph-up-arrow',
    ];
@endphp
<div class="dashboard-heading"><div><div class="eyebrow"><span></span> Admin workspace</div><h1>{{ $sectionTitles[$section] }}</h1><p>Manage {{ strtolower($sectionTitles[$section]) }} for AapkaSarthi.</p></div><a class="btn btn-outline-secondary btn-sm" href="{{ route('dashboard') }}"><i class="bi bi-arrow-left me-1"></i> Admin dashboard</a></div>
<nav class="d-flex flex-wrap gap-2 mb-4" aria-label="Admin sections">@foreach($sectionTitles as $key => $title)<a class="btn btn-sm {{ $section === $key ? 'btn-forest' : 'btn-outline-secondary' }}" href="{{ route('admin.manage', $key) }}">{{ $title }}</a>@endforeach</nav>

@if($section === 'users')
    <section class="portal-section mt-0">
        <div class="section-title"><div><span class="eyebrow"><span></span> Accounts</span><h2>Users</h2></div><button class="btn btn-forest btn-sm" data-bs-toggle="modal" data-bs-target="#createUserModal"><i class="bi bi-plus-lg me-1"></i>Add patient</button></div>
        <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>State</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse($users as $managedUser)<tr><td>{{ $managedUser->name }}</td><td>{{ $managedUser->email }}</td><td>{{ ucfirst($managedUser->role) }}</td><td>{{ $managedUser->blocked_at ? 'Blocked' : 'Active' }}</td><td><div class="d-flex justify-content-end gap-2"><button class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#editUser{{ $managedUser->id }}">Edit</button><form method="POST" action="{{ route('admin.users.block', $managedUser) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary btn-sm">{{ $managedUser->blocked_at ? 'Activate' : 'Block' }}</button></form>@if($managedUser->id !== auth()->id())<form method="POST" action="{{ route('admin.users.delete', $managedUser) }}" onsubmit="return confirm('Permanently delete this user and dependent records?')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Delete</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="text-secondary">No users found.</td></tr>@endforelse
        </tbody></table></div>{{ $users->links() }}
    </section>
    <div class="modal fade" id="createUserModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Create patient account</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.users.store') }}">@csrf
        <label class="form-label">Name</label><input class="form-control mb-2" name="name" required><label class="form-label">Email</label><input class="form-control mb-2" name="email" type="email" required><label class="form-label">Phone</label><input class="form-control mb-2" name="phone"><label class="form-label">Password</label><input class="form-control mb-2" name="password" type="password" minlength="8" required><label class="form-label">Confirm password</label><input class="form-control mb-3" name="password_confirmation" type="password" minlength="8" required><button class="btn btn-forest btn-sm">Create account</button>
    </form></div></div></div></div>
    @foreach($users as $managedUser)<div class="modal fade" id="editUser{{ $managedUser->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Edit user</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p class="small text-secondary">{{ ucfirst($managedUser->role) }} · {{ $managedUser->blocked_at ? 'Blocked' : 'Active' }}</p><form method="POST" action="{{ route('admin.users.update', $managedUser) }}">@csrf @method('PUT')<label class="form-label">Name</label><input class="form-control mb-2" name="name" value="{{ $managedUser->name }}" required><label class="form-label">Email</label><input class="form-control mb-2" name="email" type="email" value="{{ $managedUser->email }}" required><label class="form-label">Phone</label><input class="form-control mb-3" name="phone" value="{{ $managedUser->phone }}"><button class="btn btn-forest btn-sm">Save changes</button></form></div></div></div></div>@endforeach
@elseif($section === 'guides')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Guide applications</span><h2>Guides</h2></div><button class="btn btn-forest btn-sm" data-bs-toggle="modal" data-bs-target="#createGuideModal"><i class="bi bi-plus-lg me-1"></i>Add guide</button></div>
        <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Guide</th><th>City</th><th>Experience</th><th>Hospitals</th><th>Status</th><th></th></tr></thead><tbody>
        @forelse($guides as $guide)@php($guideStatus = $guide->status ?? ($guide->is_verified ? 'verified' : 'pending'))<tr><td><strong>{{ $guide->user->name }}</strong><small class="d-block text-secondary">{{ $guide->user->email }}</small></td><td>{{ $guide->city ?: 'Not set' }}</td><td>{{ $guide->years_experience }} years</td><td>{{ $guide->hospitals->pluck('name')->join(', ') ?: 'None' }}</td><td>{{ ucfirst($guideStatus) }}</td><td class="text-end"><button class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#editGuide{{ $guide->id }}">Edit guide</button></td></tr>@empty<tr><td colspan="6" class="text-secondary">No guide profiles found.</td></tr>@endforelse
        </tbody></table></div>{{ $guides->links() }}
    </section>
    <div class="modal fade" id="createGuideModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Create guide account</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.guides.store') }}">@csrf<label class="form-label">Name</label><input class="form-control mb-2" name="name" required><label class="form-label">Email</label><input class="form-control mb-2" name="email" type="email" required><label class="form-label">Phone</label><input class="form-control mb-2" name="phone"><label class="form-label">City</label><input class="form-control mb-2" name="city" maxlength="120" required><label class="form-label">Password</label><input class="form-control mb-2" name="password" type="password" minlength="8" required><label class="form-label">Confirm password</label><input class="form-control mb-3" name="password_confirmation" type="password" minlength="8" required><button class="btn btn-forest btn-sm">Create guide</button></form></div></div></div></div>
    @foreach($guides as $guide)@php($guideStatus = $guide->status ?? ($guide->is_verified ? 'verified' : 'pending'))@php($availabilityByDay = $guide->availabilities->keyBy('weekday'))<div class="modal fade" id="editGuide{{ $guide->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title fs-5">{{ $guide->user->name }}</h2><small class="text-secondary">Guide profile, availability and verification</small></div><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.guides.update', $guide) }}">@csrf @method('PUT')<div class="row g-2">
        <div class="col-md-3"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ $guide->user->name }}" required></div><div class="col-md-3"><label class="form-label">Email</label><input class="form-control" name="email" type="email" value="{{ $guide->user->email }}" required></div><div class="col-md-3"><label class="form-label">Phone</label><input class="form-control" name="phone" value="{{ $guide->user->phone }}"></div><div class="col-md-3"><label class="form-label">City</label><input class="form-control" name="city" value="{{ $guide->city }}" maxlength="120" required></div>
        <div class="col-md-6"><label class="form-label">Bio</label><textarea class="form-control" name="bio" rows="2" maxlength="1200">{{ $guide->bio }}</textarea></div><div class="col-md-6"><label class="form-label">Languages</label><input class="form-control" name="languages" value="{{ is_array($guide->languages) ? implode(', ', $guide->languages) : $guide->languages }}"></div>
        <div class="col-md-4"><label class="form-label">Specialization</label><input class="form-control" name="specialization" value="{{ $guide->specialization }}" maxlength="160"></div><div class="col-md-4"><label class="form-label">Years experience</label><input class="form-control" name="years_experience" type="number" min="0" max="60" value="{{ $guide->years_experience }}" required></div><div class="col-md-4"><label class="form-label">Hourly fee (₹)</label><input class="form-control" name="hourly_rate" type="number" min="0" max="100000" step="0.01" value="{{ $guide->hourly_rate }}" required></div>
        <div class="col-md-4"><label class="form-label">Verification</label><select class="form-select" name="status">@foreach(['pending', 'verified', 'rejected', 'suspended'] as $status)<option value="{{ $status }}" @selected($guideStatus === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-8 d-flex align-items-end"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_available" value="1" @checked($guide->is_available)> Accepting bookings</label></div>
        <div class="col-12"><fieldset><legend class="form-label">Hospitals</legend><div class="row g-1">@foreach($hospitals as $hospital)<div class="col-md-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="hospitals[]" value="{{ $hospital->id }}" @checked($guide->hospitals->contains('id', $hospital->id))> {{ $hospital->name }}</label></div>@endforeach</div></fieldset></div>
        <div class="col-12"><fieldset><legend class="form-label">Weekly availability</legend><div class="row g-2">@foreach(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as $weekday => $weekdayName)@php($slot = $availabilityByDay->get($weekday))<div class="col-md-6 col-lg-4"><label class="form-label">{{ $weekdayName }}</label><div class="d-flex gap-2"><input class="form-control" type="time" name="availability[{{ $weekday }}][start_time]" value="{{ $slot ? substr($slot->start_time, 0, 5) : '' }}" aria-label="{{ $weekdayName }} start"><input class="form-control" type="time" name="availability[{{ $weekday }}][end_time]" value="{{ $slot ? substr($slot->end_time, 0, 5) : '' }}" aria-label="{{ $weekdayName }} end"></div><input type="hidden" name="availability[{{ $weekday }}][weekday]" value="{{ $weekday }}"></div>@endforeach</div></fieldset></div>
        </div><button class="btn btn-forest btn-sm mt-3">Save guide</button></form><hr><div class="d-flex flex-wrap gap-2 align-items-end">@if($guide->document_path)<a class="btn btn-outline-secondary btn-sm" href="{{ route('admin.guides.documents.view', $guide) }}" target="_blank" rel="noopener">View document</a><form method="POST" action="{{ route('admin.guides.documents.delete', $guide) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Remove document</button></form>@else<span class="small text-secondary">No document uploaded.</span>@endif<form class="d-flex gap-2 align-items-end" method="POST" enctype="multipart/form-data" action="{{ route('admin.guides.documents.upload', $guide) }}">@csrf<label class="small">Upload document<input class="form-control form-control-sm" type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="btn btn-outline-secondary btn-sm">Upload</button></form></div></div></div></div></div>@endforeach
@elseif($section === 'hospitals')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Directory</span><h2>Hospitals</h2></div><button class="btn btn-forest btn-sm" data-bs-toggle="modal" data-bs-target="#createHospital"><i class="bi bi-plus-lg me-1"></i>Add hospital</button></div>
        <form method="GET" action="{{ route('admin.manage', 'hospitals') }}" class="d-flex gap-2 mb-3"><select class="form-select form-select-sm" name="city" aria-label="Filter hospitals by city"><option value="">All cities</option>@foreach($cityOptions as $city)<option value="{{ $city }}" @selected($cityFilter === $city)>{{ $city }}</option>@endforeach</select><button class="btn btn-outline-secondary btn-sm">Filter</button></form>
        <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Hospital</th><th>Address</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($hospitals as $hospital)<tr><td><strong>{{ $hospital->name }}</strong><small class="d-block text-secondary">{{ $hospital->city }} · {{ $hospital->type }}</small></td><td>{{ $hospital->address }}</td><td>{{ $hospital->is_active ? 'Active' : 'Hidden' }}</td><td><div class="d-flex justify-content-end gap-2"><button class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#editHospital{{ $hospital->id }}">Edit</button><form method="POST" action="{{ route('admin.hospitals.toggle', $hospital) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary btn-sm">{{ $hospital->is_active ? 'Hide' : 'Activate' }}</button></form><form method="POST" action="{{ route('admin.hospitals.delete', $hospital) }}" onsubmit="return confirm('Delete this hospital?')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Delete</button></form></div></td></tr>@empty<tr><td colspan="4" class="text-secondary">No hospitals found.</td></tr>@endforelse</tbody></table></div>{{ $hospitals->links() }}
    </section>
    <div class="modal fade" id="createHospital" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Add hospital</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.hospitals.store') }}">@csrf<label class="form-label">Name</label><input class="form-control mb-2" name="name" required><label class="form-label">City</label><input class="form-control mb-2" name="city" list="supportedHospitalCities" required><datalist id="supportedHospitalCities">@foreach($cityOptions as $city)<option value="{{ $city }}">@endforeach</datalist><label class="form-label">Type</label><input class="form-control mb-2" name="type"><label class="form-label">Address</label><input class="form-control mb-2" name="address" required><label class="form-label">Phone</label><input class="form-control mb-2" name="phone"><label class="form-label">Image URL</label><input class="form-control mb-3" name="image_url" type="url"><button class="btn btn-forest btn-sm">Add hospital</button></form></div></div></div></div>
    @foreach($hospitals as $hospital)<div class="modal fade" id="editHospital{{ $hospital->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Edit hospital</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.hospitals.update', $hospital) }}">@csrf @method('PUT')<label class="form-label">Name</label><input class="form-control mb-2" name="name" value="{{ $hospital->name }}" required><label class="form-label">City</label><input class="form-control mb-2" name="city" value="{{ $hospital->city }}" required><label class="form-label">Type</label><input class="form-control mb-2" name="type" value="{{ $hospital->type }}"><label class="form-label">Address</label><input class="form-control mb-2" name="address" value="{{ $hospital->address }}" required><label class="form-label">Phone</label><input class="form-control mb-2" name="phone" value="{{ $hospital->phone }}"><label class="form-label">Image URL</label><input class="form-control mb-3" name="image_url" type="url" value="{{ $hospital->image_url }}"><button class="btn btn-forest btn-sm">Save changes</button></form></div></div></div></div>@endforeach
@elseif($section === 'services')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Booking catalog</span><h2>Services</h2></div><button class="btn btn-forest btn-sm" data-bs-toggle="modal" data-bs-target="#createService"><i class="bi bi-plus-lg me-1"></i>Add service</button></div>
        <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Name</th><th>Description</th><th>Base price</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($services as $service)<tr><td>{{ $service->name }}</td><td>{{ $service->description ?: 'No description' }}</td><td>₹{{ number_format((float) $service->base_price, 2) }}</td><td>{{ $service->is_active ? 'Active' : 'Inactive' }}</td><td class="text-end"><button class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#editService{{ $service->id }}">Edit</button><form class="d-inline" method="POST" action="{{ route('admin.services.delete', $service) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="text-secondary">No services configured.</td></tr>@endforelse</tbody></table></div>{{ $services->links() }}
    </section>
    <div class="modal fade" id="createService" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Add service</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.services.store') }}">@csrf<label class="form-label">Name</label><input class="form-control mb-2" name="name" required><label class="form-label">Description</label><input class="form-control mb-2" name="description"><label class="form-label">Base price (₹)</label><input class="form-control mb-3" name="base_price" type="number" min="0" step="0.01" value="0" required><button class="btn btn-forest btn-sm">Add service</button></form></div></div></div></div>
    @foreach($services as $service)<div class="modal fade" id="editService{{ $service->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Edit {{ $service->name }}</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><form method="POST" action="{{ route('admin.services.update', $service) }}">@csrf @method('PUT')<label class="form-label">Name</label><input class="form-control mb-2" name="name" value="{{ $service->name }}" required><label class="form-label">Description</label><input class="form-control mb-2" name="description" value="{{ $service->description }}"><label class="form-label">Base price (₹)</label><input class="form-control mb-2" name="base_price" type="number" min="0" step="0.01" value="{{ $service->base_price }}" required><label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($service->is_active)> Active</label><button class="btn btn-forest btn-sm">Save changes</button></form></div></div></div></div>@endforeach
@elseif($section === 'bookings')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Visit requests</span><h2>Bookings</h2></div></div><form method="GET" action="{{ route('admin.manage', 'bookings') }}" class="d-flex gap-2 mb-3"><select class="form-select form-select-sm" name="city" aria-label="Filter bookings by city"><option value="">All cities</option>@foreach($cityOptions as $city)<option value="{{ $city }}" @selected($cityFilter === $city)>{{ $city }}</option>@endforeach</select><select class="form-select form-select-sm" name="booking_status" aria-label="Filter bookings by status"><option value="">All statuses</option>@foreach(['pending', 'accepted', 'received', 'rejected', 'cancelled', 'completed'] as $status)<option value="{{ $status }}" @selected($bookingStatus === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-outline-secondary btn-sm">Filter</button></form><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Date</th><th>Visit</th><th>Patient / guide</th><th>Status</th><th></th></tr></thead><tbody>@forelse($bookings as $booking)<tr><td>{{ $booking->visit_date->format('d M Y') }}</td><td>{{ $booking->hospital->name }}<small class="d-block text-secondary">{{ $booking->hospital->city }} · {{ $booking->service }} · {{ $booking->start_time }}</small></td><td>{{ $booking->patient->name }}<small class="d-block text-secondary">{{ $booking->guideProfile->user->name }}</small></td><td>{{ ucfirst($booking->status) }}</td><td><form method="POST" action="{{ route('admin.bookings.status', $booking) }}" class="d-flex gap-1">@csrf @method('PATCH')<select class="form-select form-select-sm" name="status" aria-label="Booking status">@foreach(['pending', 'accepted', 'received', 'rejected', 'cancelled', 'completed'] as $status)<option value="{{ $status }}" @selected($booking->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-forest btn-sm">Save</button></form></td></tr>@empty<tr><td colspan="5" class="text-secondary">No bookings found for this city and status.</td></tr>@endforelse</tbody></table></div>{{ $bookings->links() }}</section>
@elseif($section === 'payments')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Transactions</span><h2>Payments</h2></div></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Reference</th><th>Patient</th><th>Hospital</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->transaction_reference ?: 'Payment #'.$payment->id }}</td><td>{{ $payment->booking->patient->name }}</td><td>{{ $payment->booking->hospital->name }}</td><td>{{ $payment->currency }} {{ number_format((float) $payment->amount, 2) }}</td><td>{{ ucfirst($payment->status) }}</td><td>{{ $payment->paid_at?->format('d M Y, H:i') ?: 'Not paid' }}</td></tr>@empty<tr><td colspan="6" class="text-secondary">No payment transactions recorded.</td></tr>@endforelse</tbody></table></div>{{ $payments->links() }}</section>
@elseif($section === 'reviews')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Customer feedback</span><h2>Reviews</h2></div></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Rating</th><th>Customer</th><th>Guide</th><th>Comment</th><th>Visibility</th><th></th></tr></thead><tbody>@forelse($reviews as $review)<tr><td>{{ $review->rating }}/5</td><td>{{ $review->booking->patient->name }}</td><td>{{ $review->booking->guideProfile->user->name }}</td><td>{{ $review->comment }}</td><td>{{ $review->is_visible ? 'Published' : 'Hidden' }}</td><td><div class="d-flex gap-2"><form method="POST" action="{{ route('admin.reviews.visibility', $review) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary btn-sm">{{ $review->is_visible ? 'Hide' : 'Publish' }}</button></form><form method="POST" action="{{ route('admin.reviews.delete', $review) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Delete</button></form></div></td></tr>@empty<tr><td colspan="6" class="text-secondary">No reviews recorded.</td></tr>@endforelse</tbody></table></div>{{ $reviews->links() }}</section>
@elseif($section === 'commission')
    <section class="portal-section mt-0"><div class="section-title"><div><span class="eyebrow"><span></span> Platform revenue</span><h2>Commission</h2></div></div><form method="POST" action="{{ route('admin.commission.update') }}" class="portal-form">@csrf @method('PUT')<div class="row g-3"><div class="col-md-5"><label class="form-label">Commission rate (%)</label><input class="form-control" name="percentage_rate" type="number" min="0" max="100" step="0.01" value="{{ $commission?->percentage_rate ?? 0 }}" required></div><div class="col-md-5"><label class="form-label">Fixed amount per booking (₹)</label><input class="form-control" name="fixed_amount" type="number" min="0" step="0.01" value="{{ $commission?->fixed_amount ?? 0 }}" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-forest">Save</button></div></div></form></section>
@endif
@endsection
